# Generated by Django 5.2.4 on 2025-07-22 04:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(validators=[api.models.Appointment.validate_future_date]),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date'], name='appointment_date_dabb59_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['professional'], name='appointment_profess_480d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='professional',
            index=models.Index(fields=['social_name'], name='professiona_social__192892_idx'),
        ),
        migrations.AddIndex(
            model_name='professional',
            index=models.Index(fields=['profession'], name='professiona_profess_38bd92_idx'),
        ),
    ]
